/**
 * runtime.routes.ts
 *
 * REST endpoints for Runtime status and control.
 *
 *   GET    /api/runtime/status
 *   POST   /api/runtime/emergency-stop
 *   POST   /api/runtime/resume
 *   GET    /api/runtime/live-feed  (SSE stream)
 */

import { Router, Request, Response } from 'express';
import { runtimeProxy } from '../../enforcement';

const router = Router();

// ── GET /api/runtime/status ───────────────────────────────────────

router.get('/status', (_req: Request, res: Response) => {
  const agentIds = runtimeProxy.getRegisteredAgentIds();
  const agentStates = agentIds.map(id => {
    const rt = runtimeProxy.getAgentRuntime(id);
    return {
      agentId: id,
      callCount: rt?.state.callTimestamps.length ?? 0,
      cumulativeFinancial: rt?.state.cumulativeFinancial ?? 0,
      activatedAt: rt?.state.activatedAt
        ? new Date(rt.state.activatedAt).toISOString()
        : null,
    };
  });

  res.json({
    emergencyStopActive: runtimeProxy.emergencyStopActive,
    zeroTrustEnabled: runtimeProxy.zeroTrustEnabled,
    registeredAgents: agentIds.length,
    agents: agentStates,
    auditLogSize: runtimeProxy.auditLog.length,
    recentDecisions: runtimeProxy.auditLog.slice(-10),
  });
});

// ── POST /api/runtime/emergency-stop ──────────────────────────────

router.post('/emergency-stop', (_req: Request, res: Response) => {
  runtimeProxy.activateEmergencyStop();
  res.json({
    emergencyStopActive: true,
    message: '🛑 Emergency stop activated — ALL agent execution halted',
  });
});

// ── POST /api/runtime/resume ──────────────────────────────────────

router.post('/resume', (_req: Request, res: Response) => {
  runtimeProxy.deactivateEmergencyStop();
  res.json({
    emergencyStopActive: false,
    message: '✅ Emergency stop deactivated — normal operation resumed',
  });
});

// ── GET /api/runtime/live-feed ────────────────────────────────────
//    Server-Sent Events stream of enforcement decisions.
//
//    The client connects once and receives real-time events as they
//    are generated by the runtime proxy's audit log.

router.get('/live-feed', (req: Request, res: Response) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.setHeader('X-Accel-Buffering', 'no');

  // Send initial heartbeat
  res.write(`data: ${JSON.stringify({ type: 'connected', timestamp: new Date().toISOString() })}\n\n`);

  // Track the last sent index
  let lastIndex = runtimeProxy.auditLog.length;

  // Poll every 500ms for new entries
  const interval = setInterval(() => {
    const log = runtimeProxy.auditLog;
    if (log.length > lastIndex) {
      for (let i = lastIndex; i < log.length; i++) {
        res.write(`data: ${JSON.stringify(log[i])}\n\n`);
      }
      lastIndex = log.length;
    }
  }, 500);

  // Heartbeat every 15s to keep connection alive
  const heartbeat = setInterval(() => {
    res.write(`: heartbeat\n\n`);
  }, 15000);

  // Cleanup on client disconnect
  req.on('close', () => {
    clearInterval(interval);
    clearInterval(heartbeat);
  });
});

export default router;
